CREATE DATABASE Proyecto3_B84211_B87107
USE Proyecto3_B84211_B87107
CREATE TABLE tb_USUARIO (
CEDULA INT PRIMARY KEY NOT NULL
,CONTRASENA VARCHAR(20) NOT NULL
)

CREATE TABLE tb_PACIENTE (
CEDULA INT NOT NULL
,NOMBRE VARCHAR(100) NOT NULL
,EDAD INT NOT NULL
,TPSANGRE VARCHAR(10) NOT NULL
,ESTADOCIVIL VARCHAR(20) NOT NULL
,TELEFONO INT NOT NULL
,DOMICILIO VARCHAR(300) NOT NULL
,FOREIGN KEY (CEDULA) REFERENCES tb_USUARIO(CEDULA)
)

CREATE TABLE tb_MEDICO (
CEDULA INT PRIMARY KEY NOT NULL
,CODIGO VARCHAR(20) NOT NULL
,CONTRASENA VARCHAR(20) NOT NULL
)

CREATE TABLE tb_ALERGIA (
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL
,NOMBRE VARCHAR(20) NOT NULL
,DECRIPCION VARCHAR(100) NOT NULL
)


CREATE TABLE tb_VACUNA (
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL
,NOMBRE VARCHAR(20) NOT NULL
,DECRIPCION VARCHAR(100) NOT NULL
)

CREATE TABLE tb_CITA(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL
,CEDULA INT NOT NULL
,CENTRO_SALUD VARCHAR(100) NOT NULL
,FECHA DATETIME NOT NULL
,ESPECIALIDAD VARCHAR(20) NOT NULL
,DECRIPCION VARCHAR(20) NOT NULL
,FOREIGN KEY (CEDULA) REFERENCES tb_USUARIO(CEDULA)
)

CREATE TABLE tb_ALERGIA_PACIENTE(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL
,CEDULA INT NOT NULL
,ID_ALERGIA INT NOT NULL
,FECHA DATETIME NOT NULL
,MEDICAMENTOS VARCHAR(200) NOT NULL
,FOREIGN KEY (ID_ALERGIA) REFERENCES tb_ALERGIA(ID)
,FOREIGN KEY (CEDULA) REFERENCES tb_USUARIO(CEDULA)
)

ALTER TABLE  tb_ALERGIA_PACIENTE ADD DESCRIPCION varchar(100);

CREATE TABLE tb_VACUNA_PACIENTE(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL
,CEDULA INT NOT NULL
,ID_VACUNA INT NOT NULL
,FECHA_APLICACION DATE NOT NULL
,FECHA_PROX_DOS DATE NOT NULL
,FOREIGN KEY (ID_VACUNA) REFERENCES tb_VACUNA(ID)
,FOREIGN KEY (CEDULA) REFERENCES tb_USUARIO(CEDULA)
)

ALTER TABLE tb_VACUNA_PACIENTE ADD DESCRIPCION varchar(100);

--INSERT

INSERT INTO [dbo].[tb_USUARIO]
           ([CEDULA]
           ,[CONTRASENA])
     VALUES
           (305240689
           ,'123')


INSERT INTO [dbo].[tb_MEDICO]
           ([CEDULA]
           ,[CODIGO]
           ,[CONTRASENA])
     VALUES
           (305000500
           ,'Medico1'
           ,'123')


INSERT INTO [dbo].[tb_PACIENTE]
           ([CEDULA]
           ,[NOMBRE]
           ,[EDAD]
           ,[TPSANGRE]
           ,[ESTADOCIVIL]
           ,[TELEFONO]
           ,[DOMICILIO])
     VALUES
           (305240689
           ,'Maria Perez'
           ,22
           ,'O+'
           ,'Soltera'
           ,89632548
           ,'Cartago,Turrialba,Turrialba')

INSERT INTO [dbo].[tb_VACUNA]
           ([NOMBRE]
           ,[DECRIPCION])
     VALUES
           ('BCG','Protege contra Tuberculosis')
		   ,
		   ('Hepatitis B','Protege contra Hepatitis B')
		    ,		    
		   ('Hib tipo b','Protege contra Meningitis,Aaemophilus influenzoe')
		    ,
		   ('D.P.T.','Protege contra Difteria,Tosferina,Tétanos')
		    ,
		   ('V.O.P.','Protege contra Poliomielitis')
		    ,
		   ('S.R.P.','Protege contra Sarampeón,Rubéola,Paperas')
		    ,
		   ('D.T.','Protege contra Difteria,Tétanos')
		   ,
		   ('Rotavirus','Protege contra Rotavirus')
		   ,
		   ('Covid','Protege contra Covid')

---Procedimientos almacenados



CREATE PROCEDURE sp_LOGIN
@param_CEDULA int
,@param_CODIGO varchar(20)
,@param_CONTRASENA varchar(20)

AS 
BEGIN
	IF EXISTS(
	SELECT * FROM  [dbo].[tb_MEDICO]
	WHERE [CEDULA] = @param_CEDULA 
	AND  [CODIGO] = @param_CODIGO
	AND [CONTRASENA] = @param_CONTRASENA
	)
	BEGIN
		SELECT 
		1 AS EXISTE
		,[CEDULA]
		,[CODIGO]
		,[CONTRASENA]
		FROM [dbo].[tb_MEDICO]
		WHERE [CEDULA] = @param_CEDULA
	END
	ELSE
	BEGIN
	 SELECT 0 AS EXISTE,' ' AS CEDULA,' ' AS CODIGO,' ' AS CONTRASENA
	END

END

EXEC sp_LOGIN  305000500 ,'Medico1' ,'123'

--Select vacunas

CREATE PROCEDURE sp_SELECT_VACUNAS
AS 
BEGIN
SELECT [ID]
      ,[NOMBRE]
      ,[DECRIPCION]
  FROM [dbo].[tb_VACUNA]

END

exec sp_SELECT_VACUNAS



CREATE PROCEDURE sp_SELECT_VACUNA_ID
@param_ID int
AS 
BEGIN
SELECT 
      [DECRIPCION]
  FROM [dbo].[tb_VACUNA]
  WHERE [ID] = @param_ID

END

exec sp_SELECT_VACUNA_ID 1

--Select CEDULAS

CREATE PROCEDURE sp_SELECT_CEDULAS
AS 
BEGIN
SELECT [CEDULA]
      ,[NOMBRE]
  FROM [dbo].[tb_PACIENTE]

END

exec sp_SELECT_CEDULAS


ALTER PROCEDURE sp_INSERT_VACUNA_PACIENTE
@param_CEDULA int
,@param_ID_VACUNA int
,@param_FECHA_APLICACION date
,@param_FECHA_PROX_DOS date
,@param_DESCRIPCION varchar(100)
AS 
BEGIN
INSERT INTO [dbo].[tb_VACUNA_PACIENTE]
           ([CEDULA]
           ,[ID_VACUNA]
           ,[FECHA_APLICACION]
           ,[FECHA_PROX_DOS]
           ,[DESCRIPCION])
     VALUES
           (@param_CEDULA
           ,@param_ID_VACUNA
           ,@param_FECHA_APLICACION
           ,@param_FECHA_PROX_DOS
           ,@param_DESCRIPCION)
END

EXECUTE [dbo].[sp_INSERT_VACUNA_PACIENTE] 
   305240689
  ,2
  ,'2021-07-14'
  ,'2031-07-14'
  ,'Protege contra Hepatitis B'


CREATE PROCEDURE sp_SELECT_VACUNA_PACIENTE
@param_CEDULA int
AS 
BEGIN

SELECT VP.[ID]
      ,VP.[CEDULA]
      ,VP.[ID_VACUNA]
	  ,V.NOMBRE
      ,VP.[FECHA_APLICACION]
      ,VP.[FECHA_PROX_DOS]
      ,VP.[DESCRIPCION]
	  
  FROM [dbo].[tb_VACUNA_PACIENTE] VP
  LEFT JOIN [dbo].[tb_VACUNA] V
	ON VP.ID_VACUNA = V.ID
	WHERE VP.CEDULA = @param_CEDULA
END

  
EXEC sp_SELECT_VACUNA_PACIENTE 305240689

CREATE PROCEDURE sp_DELETE_VACUNA_PACIENTE
@param_ID int
AS 
BEGIN
DELETE FROM [tb_VACUNA_PACIENTE]
		  WHERE [ID]=@param_ID
END

EXEC sp_DELETE_VACUNA_PACIENTE 1
  

CREATE PROCEDURE sp_DELETE_VACUNA_PACIENTE
@param_ID int
,@param_CEDULA int
,@param_ID_VACUNA int
,@param_FECHA_APLICACION date
,@param_FECHA_PROX_DOS date
,@param_DESCRIPCION varchar(100)
AS 
BEGIN
UPDATE [tb_VACUNA_PACIENTE]
   SET [CEDULA] = <CEDULA, int,>
      ,[ID_VACUNA] = <ID_VACUNA, int,>
      ,[FECHA_APLICACION] = <FECHA_APLICACION, date,>
      ,[FECHA_PROX_DOS] = <FECHA_PROX_DOS, date,>
      ,[DESCRIPCION] = <DESCRIPCION, varchar(100),>
 WHERE <Search Conditions,,>
END